name: Client App Build and Test

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build-and-test-client:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Generate DBus machine ID
      run: sudo sh -c 'dbus-uuidgen > /var/lib/dbus/machine-id'

    - name: Start DBus daemon
      run: sudo dbus-daemon --system --fork

    - name: Install Dependencies
      run: |
        cd client
        npm install

    - name: Install and start Xvfb
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        export DISPLAY=':99.0'
        Xvfb :99 -screen 0 1280x720x24 > /dev/null 2>&1 &

    - name: Build Client App
      run: |
        cd client
        npm run build
        npm run strace electron -- --disable-gpu --enable-features=UseOzonePlatform --ozone-platform=headless --disable-software-rasterizer --disable-dev-shm-usage --no-sandbox
      env:
        DISPLAY: ':99.0'
        ELECTRON_ENABLE_LOGGING: true