name: Client App Build and Test

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

permissions: 
  contents: write

jobs:
  build-and-test-client:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Compile Electron App
      uses: samuelmeuli/action-electron-builder@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        package_manager: npm
        skip_build: false
