name: Client App Build and Test

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build-and-test-client:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        cd client
        npm install

    - name: Build Client App
      run: |
        cd client
        npm run build
        yarn electron