---
name: Super-Linter

permissions:
  contents: read
  statuses: write

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Super-Linter
        uses: super-linter/super-linter@4ce20838b8ab83717e78138c5b3a1407148e0918 # v8.7.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT: false
          VALIDATE_CSS_PRETTIER: true
          VALIDATE_HTML_PRETTIER: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          VALIDATE_JSON_PRETTIER: true
          VALIDATE_MARKDOWN_PRETTIER: true
          VALIDATE_YAML_PRETTIER: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_SHELL_SHFMT: true
